In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')


from sklearn.preprocessing import LabelEncoder , OrdinalEncoder


## Models
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor , AdaBoostRegressor
from xgboost import XGBRegressor

In [2]:
df = pd.read_csv('StudentsPerformance.csv')

In [3]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [5]:
target_column = "math score"

In [6]:
coulmn_summary = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "Missing Values":df.isnull().sum(),
    "unique_values":df.nunique(),
})

In [7]:
coulmn_summary

                             dtype  Missing Values  unique_values
gender                         str               0              2
race/ethnicity                 str               0              5
parental level of education    str               0              6
lunch                          str               0              2
test preparation course        str               0              2
math score                   int64               0             81
reading score                int64               0             72
writing score                int64               0             77

In [8]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [11]:
df[target_column].describe().to_frame().T

             count    mean       std  min   25%   50%   75%    max
math score  1000.0  66.089  15.16308  0.0  57.0  66.0  77.0  100.0

In [12]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [18]:
categorical_features = df.drop(columns=[target_column]).select_dtypes(include="object").columns.tolist()
numerical_features = df.drop(columns=[target_column]).select_dtypes(exclude="object").columns.tolist()

In [17]:
categorical_features

['gender',
 'race/ethnicity',
 'parental level of education',
 'lunch',
 'test preparation course']

In [19]:
numerical_features

['reading score', 'writing score']

In [ ]:
df['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [26]:
x = df.drop(columns=[target_column])
y = df[target_column]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
label_encoder = LabelEncoder()

In [27]:
x_train['gender'] = label_encoder.fit_transform(x_train['gender'])
x_test['gender'] = label_encoder.transform(x_test['gender'])

x_train['race/ethnicity'] = label_encoder.fit_transform(x_train['race/ethnicity'])
x_test['race/ethnicity'] = label_encoder.transform(x_test['race/ethnicity'])

x_train['lunch'] = label_encoder.fit_transform(x_train['lunch'])
x_test['lunch'] = label_encoder.transform(x_test['lunch'])

x_train['test preparation course'] = label_encoder.fit_transform(x_train['test preparation course'])
x_test['test preparation course'] = label_encoder.transform(x_test['test preparation course'])

In [28]:
df['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [ ]:
ord_encoder = OrdinalEncoder(categories=[['some high school',
                                          'high school',
                                          'some college',
                                          "associate's degree",
                                          "bachelor's degree", 
                                          "master's degree"]])

In [30]:
x_train['parental level of education'] = ord_encoder.fit_transform(x_train[['parental level of education']])
x_test['parental level of education'] = ord_encoder.transform(x_test[['parental level of education']])

In [33]:
x_test.info()

<class 'pandas.DataFrame'>
Index: 200 entries, 521 to 78
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       200 non-null    int64
 1   race/ethnicity               200 non-null    int64
 2   parental level of education  200 non-null    float64
 3   lunch                        200 non-null    int64
 4   test preparation course      200 non-null    int64
 5   reading score                200 non-null    int64
 6   writing score                200 non-null    int64
dtypes: float64(1), int64(6)
memory usage: 12.5 KB

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor , AdaBoostRegressor
from xgboost import XGBRegressor

In [34]:
models = {
    "LR": LinearRegression(),
    "SVM": SVR(),
    "KNN": KNeighborsRegressor(),
    "DT": DecisionTreeRegressor(),
    "RF": RandomForestRegressor(),
    "AdaBoost": AdaBoostRegressor(),
    "XGBoost": XGBRegressor()
}

In [45]:
list(models.keys())[2]

'KNN'

In [35]:
def evaluate_model(act,pred,model_name):
    score = r2_score(act,pred)
    print(f"R2 Score: {score} --> model : {model_name}")
    return score

In [50]:
dicy={'name':'Ahmed'}

In [53]:
dicy['age'] = 25

In [54]:
dicy

{'name': 'Ahmed', 'age': 25}

In [47]:
model_scores = {}

for i in range(len(models)):
    model = list(models.values())[i]
    model_name = list(models.keys())[i]
    
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    
    score = evaluate_model(y_test,y_pred,model_name)
    model_scores[model_name] = score

R2 Score: 0.8853662423455011 --> model : LR
R2 Score: 0.6200768115072823 --> model : SVM
R2 Score: 0.6733988552567125 --> model : KNN
R2 Score: 0.7432998655370464 --> model : DT
R2 Score: 0.8497459647780734 --> model : RF
R2 Score: 0.8546305424481118 --> model : AdaBoost
R2 Score: 0.8313145637512207 --> model : XGBoost

In [48]:
model_scores

{'LR': 0.8853662423455011,
 'SVM': 0.6200768115072823,
 'KNN': 0.6733988552567125,
 'DT': 0.7432998655370464,
 'RF': 0.8497459647780734,
 'AdaBoost': 0.8546305424481118,
 'XGBoost': 0.8313145637512207}

In [57]:
max(list(model_scores.values()))

0.8853662423455011